stages:          # List of stages for jobs, and their order of execution
  - build
  - lint

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  before_script:
    - apt-get update --yes
    - apt-get install --yes cmake
    - apt-get install --yes qt6-base-dev
  script:
    - mkdir ../debug
    - cd ../debug
    - cmake ../silent-edge
    - cmake --build .

lint-job:
  stage: lint
  before_script:
    - apt-get update --yes
    - apt-get install clang-tidy --yes
  script:
    - bash lint.sh